region: us
version: '2'
authtoken: 2on6Js0WKmE9X6qKMQz9OVsadHf_6q138cZ4e72mhs325W8HN
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  plivo-app:
    addr: plivo-app:8002
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http